spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URI:}
    username: ${POSTGRES_USER:}
    password: ${POSTGRES_PASSWORD:}
    hikari:
      maximum-pool-size: ${CONNECTION_POOL_SIZE:2}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  threads:
    virtual:
      enabled: true

  data:
    redis:
      host: localhost
      port: 6379

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  application:
    version: 1.0
    verification:
      expiry-minutes: 15

send-grid:
  api-key: YUMMY_TOKEN
  mail:
    from: YUMMY_EMAIL
  template:
    register: YUMMY

security:
  authentication:
    jwt:
      key-store: ${KEY_STORE:trackee.jks}
      key-store-password: ${KEY_STORE_PASSWORD:k0uhijUKaKWjMuL}
      key-alias: ${KEY_ALIAS:trackee}
      access-token-expires-in: ${ACCESS_TOKEN_EXPIRES_IN:60m}
      refresh-token-expires-in: ${REFRESH_TOKEN_EXPIRES_IN:7d}
      refresh-token-long-expires-in: ${REFRESH_TOKEN_EXPIRES_IN:30d}
      email-token-expires-in: ${EMAIL_TOKEN_EXPIRES_IN:10m}
    otp:
      secret: ${OTP_HMAC_SECRET}