spring:
  application:
    name: trackee

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: ${SPRING_DATASOURCE_POOL_SIZE:5}
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
      timeout: 5s

  threads:
    virtual:
      enabled: true

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: WARN

application:
  version: ${APP_VERSION:1.0}
  verification:
    expiry-minutes: 15

send-grid:
  api-key: ${SENDGRID_API_KEY}
  mail:
    from: ${SENDGRID_FROM_EMAIL}
  template:
    register: ${SENDGRID_TEMPLATE_REGISTER}

security:
  authentication:
    jwt:
      key-store: ${KEY_STORE}
      key-store-password: ${KEY_STORE_PASSWORD}
      key-alias: ${KEY_ALIAS}
      access-token-expires-in: ${ACCESS_TOKEN_EXPIRES_IN:60m}
      refresh-token-expires-in: ${REFRESH_TOKEN_EXPIRES_IN:7d}
      refresh-token-long-expires-in: ${REFRESH_TOKEN_LONG_EXPIRES_IN:30d}
      email-token-expires-in: ${EMAIL_TOKEN_EXPIRES_IN:10m}

    otp:
      secret: ${OTP_HMAC_SECRET}
