spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URI:}
    username: ${POSTGRES_USER:}
    password: ${POSTGRES_PASSWORD:}
    hikari:
      maximum-pool-size: ${CONNECTION_POOL_SIZE:2}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  application:
    version: 1.0
    verification:
      expiry-minutes: 15

  send-grid:
    api-key: YUMMY_TOKEN
    register-template: YUMMY_TOKEN

  mail:
    from: YUMMY_EMAIL

jwt:
  private-key:
    access-token: YUMMY_TOKEN
    refresh-token: YUMMY_TOKEN
  expiration:
    access-token: 3600000        # 1 hour
    refresh-token: 2592000000    # 30 days
